config/routes.rb
Buscms::Application.routes.draw do

  get "admin/export/to_xls", :as => :export_to_xls
  get "admin/export/to_pdf", :as => :export_to_pdf

  devise_for :admins
  devise_for :dealers, :controllers => {:confirmations => "confirmations"}
  devise_for :users

  match 'admin/bus_type' => 'admin/bus_types#create', :via => [:post, :put]
  match 'admin/chasis_makes' => 'admin/chasis_makes#create', :via => [:post, :put]
  match 'admin/images' => 'admin/images#create', :via => [:post, :put]
  match 'admin/inventory/search' => 'admin/inventory#search', :via => [:get, :post]
  match 'admin/inventory/update_status' => 'admin/inventory#update_status', :via => [:get, :post]
  match 'admin/leads/search_leads' => 'admin/leads#search_leads', :via => [:get, :post]
  match 'admin/export/to_xls' => 'admin/export#to_xls', :via => [:get, :post]
  match 'admin/export/to_xls_leads' => 'admin/export#to_xls_leads', :via => [:get, :post]
  match 'admin/export/to_pdf' => 'admin/export#to_pdf', :via => [:get, :post]
  match 'admin/export/to_pdf_multiple' => 'admin/export#to_pdf_multiple', :via => [:get, :post]
  match 'admin/export/to_pdf_multiple_leads' => 'admin/export#to_pdf_multiple_leads', :via => [:get, :post]
  match 'admin/export/destroy' => 'admin/inventory#destroy', :via => [:get], :as => :delete_inventory
  match 'admin/dealers/destroy' => 'admin/dealers#destroy', :via => [:get], :as => :delete_dealers
  match 'admin/users/destroy' => 'admin/users#destroy', :via => [:get], :as => :delete_users
  match 'admin/leads/destroy' => 'admin/leads#destroy', :via => [:get], :as => :delete_leads
  match 'admin/export/to_zip' => 'admin/export#to_zip', :via => [:get], :as => :zip_inventory
  match 'addtocompare' => 'home#addtocompare', :via => [:get], :as => :add_to_compare
  match 'removefromcompare' => 'home#removefromcompare', :via => [:get], :as => :remove_from_compare
  match 'admin/adds/delete_bulk_ads' => 'admin/adds#delete_bulk_ads', :via => [:get], :as => :remove_from_add
  match 'admin/adds/filter' => 'admin/adds#filter', :via => [:get], :as => :filter_add
  match '/generate_stock_id' => 'home#generate_stock_id', :via => [:get], :as => :generate_stock_id

  namespace :admin do
    resources :users
    match 'users/confirm_user_account/:id' => 'users#confirm_account', :via => [:get], :as => :confirm_user_account
    match 'dealers/confirm_dealer_account/:id' => 'dealers#confirm_account', :via => [:get], :as => :confirm_dealer_account
    match 'users/deactivate_account/:id' => 'users#deactivate_account', :via => [:get], :as => :deactivate_account
    match 'settings/update_settings' => 'settings#update_settings'
    match 'leads/send_email' => 'leads#send_email', :via => :post
    match 'leads/create_blast' => 'leads#create_blast', :via => :get
    match 'leads/remove_stock_session' => 'leads#remove_stock_session', :via => :get
    match 'leads/add_stock' => 'leads#add_stock', :via => :get
    match 'leads/blast_step3' => 'leads#blast_step3', :via => :get
    match 'leads/blast_last_step' => 'leads#blast_last_step', :via => :post
    match 'leads/send_blast' => 'leads#send_blast', :via => :post
    match 'leads/search' => 'leads#search'

    match 'search' => 'search#index'
    match 'recyclebins/restore' => 'recyclebins#restore'
    match 'recyclebins/restore_all' => 'recyclebins#restore_all'
    match 'recyclebins/restore_all_current_bin' => 'recyclebins#restore_all_current_bin'
    match 'recyclebins/empty_all' => 'recyclebins#empty_all'
    match 'recyclebins/empty_bin' => 'recyclebins#empty_bin'
    match 'recyclebins/set_delete_timer' => 'recyclebins#set_delete_timer'

    resources :images #, :only => [:index, :create, :destroy]
    resources :bus_type
    resources :inventory

    resources :contact
    resources :sold_inventory
    resources :settings
    resources :leads
    resources :chasis_makes
    resources :body_makes
    resources :dealers
    resources :stats
    resources :recyclebins
    resources :adds 
  end
  match 'listings/compare' => 'listings#compare', :via => :get
  match 'listings/search' => 'listings#search'
  match 'listings/:slug' => 'listings#index', :via => :get, :as => :buses_search, :slug => /[a-z-]{0,}/
  match 'contact/new_lead' => 'contact#new_lead', :via => [:post], :as => :new_lead

  resources :contact
  resources :listings, :only => [:show, :index, :search , :send_mail_to_friend, :send_inquiry_received_email] do
    collection do
      match 'search' => 'listings#search', :via => :get, :as => :search
      post 'send_friend_mail' => 'listings#send_mail_to_friend'
      post 'send_inquiry_received_email' => 'listings#send_inquiry_received_email'
    end
  end
  resources :dealer

  match 'cron/cron_to_update_bus_stats' => 'home#cron_to_update_bus_stats'
  match "/admin", :to => redirect("/admin/dashboard")
  match 'admin/dashboard' => 'admin/dashboard#index', :via => [:get, :post], :as => :admin_dashboard
  match 'services' => 'home#services', :as => :services
  match 'about' => 'home#about', :as => :about
  match 'contact' => 'contact#index', :as => :contact
  match 'submit_vehicle' => 'home#submit_vehicle', :as => :submit_vehicle
  match 'dealer' => 'dealer#index', :as => :dealer
  match 'add_new_vehicle' => 'home#add_new_vehicle', :as => :add_new_vehicle
  match 'compare' => 'home#compare', :as => :compare
  match 'temp' => 'temp_uploader#upload' , :as => :temp
  match '/admin/adds/update' => 'admin/adds#update'

  root :to => 'listings#index'

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_filter :count_hits
  layout "new_desgin"

  def index
    @bus_types = BusType.all
    order = params[:sort].blank? ? 'created_at-ASC' : params[:sort]
    if params[:search_field]
      @q = BusType.find_by_slug(params[:search_field]).buses.where(:live => "yes").order(order.gsub('-', ' ')).search(params[:q]) rescue Bus.where(:live => "yes").order(order.gsub('-', ' ')).search(params[:q])
    else
      unless params["q"].blank?
        params[:q][:live_eq] = "yes"
        params[:q][:state_id_eq] = params[:q][:state_id_eq].to_i unless params[:q][:state_id_eq].blank?
        params[:q][:passengers_gteq] = params[:q][:passengers_lteq].to_i == 1000 ? 50 : params[:q][:passengers_lteq].to_i - 10 unless params[:q][:passengers_lteq].blank?
      end
      bus_type = BusType.find_by_slug(params[:slug])
      @q = Bus.where(:live => "yes", :bus_type_id => '').order(order.gsub('-', ' ')).search(params[:q]) if bus_type.blank? and params[:slug].present?
      @q = BusType.find_by_slug(params[:slug]).buses.where(:live => "yes").order(order.gsub('-', ' ')).search(params[:q]) rescue Bus.where(:live => "yes").order(order.gsub('-', ' ')).search(params[:q]) unless bus_type.blank? and params[:slug].present?
    end
    if params[:search_field] and BusType.find_by_slug(params[:search_field]).blank?
      @all = [].paginate :page => params[:page], :per_page => params[:display].blank? ? 20 : params[:display]
    else
      @all = @q.result(:distinct => true).paginate :page => params[:page], :per_page => params[:display].blank? ? 20 : params[:display]

    end
  end


  def show

    @bus_types = BusType.all
    @listing = Bus.where(:live => "yes").find_by_stock_id(params[:id]) || not_found
    @related_buses= @listing.bus_type.buses.order("RAND()").limit(3)
    @lead = @listing.leads.build
    @compare_list = Bus.where(:stock_id => session[:buses])
    respond_to do |format|
      format.html
      format.pdf do
        #pdf = ListingPDF.new(@listing, view_context)
        pdf = ListingPDF.new(view_context)
        unless dealer_signed_in?
          pdf.pdf_for_bus(@listing)
        else
          pdf.pdf_for_bus(@listing, current_dealer)
        end
        send_data pdf.render, filename: "#{@listing.stock_id}_EXPORT.pdf", type: "application/pdf", disposition: "inline"
      end
    end
  end

  def send_mail_to_friend
    ContactsMailer.send_friend_mail(params[:friend]).deliver
    flash[:notice] = "Mail sent Successfully"
    redirect_to params[:friend][:friends_url]
  end

  def send_inquiry_received_email
    ContactsMailer.send_inquiry_received_email(params[:inquirename], params[:inquiremail]).deliver
    ContactsMailer.send_inquiry_received_admin(params[:inquirename], params[:inquiremail], params[:comments]).deliver
    flash[:notice] = "Inquiry Received"
    redirect_to "/listings/#{params[:back_to]}"
  end

  def search
    index
    render :index
  end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_ads_panel.html.haml
#ads_panel
  - unless Add.where("status = #{true}").blank?
    - Add.where(:status => true).order("priority ASC").select{|a|a.end && a.end > Time.now}.each do |f|
      %div{:id => "ad_priority#{f.priority}"}
        = link_to (image_tag f.image.url) ,f.url , :target => '_blank'

app/views/listings/_send_friend.html.haml
#dialog-form.dialog-form{:title => "Send to a Friend"}
  %p.validateTips All form fields are required.
  = form_for :friend , :url => send_friend_mail_listings_path, :method => :post , :html => { :id => 'form-mail' }  do |f|
    %fieldset
      = f.label :name , "Name:"
      = f.text_field :name , :id => "name" , :class => ".text .ui-widget-content .ui-corner-all .fulle" , :size => 30
      %br/
      = f.label :email , "Email:"
      = f.text_field :email , :id => "email" , :class => ".text .ui-widget-content .ui-corner-all" , :size => 30
      %br/
      = f.label :friends_email , "Friends Email:"
      = f.text_field :friends_email , :id => "friends_email" , :class => ".text .ui-widget-content .ui-corner-all" , :size => 25
      %br/
      = f.hidden_field :friends_url , :value =>  "#{url_for(:only_path => false)}"

app/views/listings/index.html.haml
= render :partial => "shared/new_design/advance_search"
#listing_content
  / inventory area start
  #listing_area
    #listing_results
      %h2
        %span.large_greytext
          =@all.count.to_s + " - "
          Buses for Sale
      #display_dropdown
        %p.float_left.form_text Display:
        %select.display_select
          %option{:value => 20 , selected: params[:display] == '10' } 20
          %option{:value => 40 , selected: params[:display] == '20' } 40
          %option{:value => 80 , selected: params[:display] == '40' } 80
          %option{:value => 100 , selected: params[:display] == '60' } 100
    / pagination start
    .pagination
      = will_paginate @all , :previous_label => '« previous', :next_label => 'next »' , :renderer => PaginationListLinkRenderer
    #sort_dropdown
      %p.float_left.form_text Sort:
      %select.sort_select
        %option{:value => "created_at-ASC" , selected: params[:sort] == "created_at-ASC"} New to Old
        %option{:value => "created_at-DESC" , selected: params[:sort] ==  "created_at-DESC" } Old to New
        %option{:value => "price-ASC" , selected: params[:sort] == "price-ASC" } Price: Low to High
        %option{:value => "price-DESC" , selected: params[:sort] == "price-DESC" } Price: High to Low
        %option{:value => "year-ASC" , selected: params[:sort] == "year-ASC" } Year: New to Old
        %option{:value => "year-DESC" , selected: params[:sort] == "year-DESC" } Year: Old to New
        %option{:value => "mileage-ASC" , selected: params[:sort] == "mileage-ASC" } Mileage: Low to High
        %option{:value => "mileage-DESC" , selected: params[:sort] == "mileage-DESC"  } Mileage: High to Low
    / sort by drop down ends
    / inventory item start
    - @all.each do |bus|
      .listing_item_panel
        .listing_item_price_panel
          %p.listing_price
            = bus.price.blank? ? "NA" : number_to_currency(bus.price_on_site, :precision => 0)
            %span.currency= bus.location == "USA" ? "USD" : "CDN"
          .detail_btn
            %a{:href => "/listings/#{bus.stock_id}"} Details
          = link_to "View compare list" , compare_path , :class => "compare_btn"
          -#%a.compare_btn{:href => "#"} View compare list
        .listing_item_detail
          .inventory_thumbnail
            %a{:href => "/listings/#{bus.stock_id}"}
              = image_tag bus.images.first.image_url(:thumb), :width => "125px", :height => "87px" if bus.images.first
          .listing_item_info
            .listing_item_title
              %a{:href => "/listings/#{bus.stock_id}"}
                = bus.year
                = bus.body_make.name
                = bus.body_model
            .listing_description
              %p Mileage:
              %p Capacity:
              %p Stock Number:
            .listing_description2
              %p= ( (number_with_delimiter bus.mileage.to_i)).to_s + (bus.location == "USA" ? " mi" : " kms")
              %p
                =bus.passengers
                Passangers
              %p=bus.stock_id
        .listing_compare
          %form{:action => ""}
            - a = session[:buses].find_index(bus.stock_id) unless session[:buses].blank?
            %input{:onclick => "submit_add_to_compare('#{bus.stock_id}',this)", :type => "checkbox", :checked => a.blank? ? false: true, :id => "chk_#{bus.stock_id}" }/
          %p.comparebox_text
            Add to compare list
    .pagination
      = will_paginate @all , :previous_label => '« previous', :next_label => 'next »' , :renderer => PaginationListLinkRenderer

    / inventory item ends

  = render :partial => "listings/ads_panel"

  .clearfix

  = render :partial => "shared/compare_toolbar"

app/views/listings/show-1.html.erb
<%= content_for :title, "Vehicle Details - #{@listing.year} #{@listing.body_model}"%>
<style type="text/css">
  #lead_country, #lead_state{
  	    border: 1px solid #999999;
  	    height: 23px;
  	    margin-left: 11px;
  	    width: 231px;
  	    margin-bottom:12px;
  }
</style>
<div class="pageContainer" id="detailedContainer">
  <div class="pageContent">
    <!-- box start -->
    <div class="box">
      <div class="detailedBoxLargeTop"></div>
      <div class="detailedBoxLargeContent"> <%= link_to image_tag("/assets/backToInventoryBtnBg.png"), :back, :class => "backToInventory" %><a href="" class="printPage" onclick="window.print();return false;"><img src="/assets/printBtnBg.png" alt="" /></a>


        <div class="detailedHeadings">

        	
          <h3><%= @listing.year %> <%= @listing.body_model %></h3>
          <h2><%= number_to_currency(@listing.price_on_site, :precision => 0) %></h2>
        </div>
        <p class="stockNumber">Stock Number: <%= @listing.stock_id %> </p>
        <!-- table and gallery container start -->
        <div class="gallerySpecsContainer">        	
          <div class="vehicleInfo">
            <h4 class="customTitle4">Specifications</h4>
            <table class="vehicleSpecs">
              <tr>
                <td class="vehicleSpecsName">Year:</td>
                <td><%= @listing.year %></td>
              </tr>

              <tr>
                <td class="vehicleSpecsName">Bus Type:</td>
                <td><%= @listing.bus_type.name %></td>
              </tr>
              <tr>
                <td class="vehicleSpecsName">Chassis Make:</td>
                <td><%= @listing.chasis_make.name %></td>

              </tr>
              <tr>
                <td class="vehicleSpecsName">Chassis Model:</td>
                <td><%= @listing.chasis_model %></td>
              </tr>
              <tr>
                <td class="vehicleSpecsName">Body Make:</td>
                <td><%= @listing.body_make.name %></td>
              </tr>
              <tr>
                <td class="vehicleSpecsName">Body Model:</td>
                <td><%= @listing.body_model %></td>
              </tr>
              <tr>

                <td class="vehicleSpecsName">Engine:</td>
                <td><%= @listing.engine %></td>
              </tr>
              <tr>
                <td class="vehicleSpecsName">Mileage:</td>
                <td><%= number_to_human(@listing.mileage, :units => :distance, :seperator => ",") %></td>
              </tr>

              <tr>
                <td class="vehicleSpecsName">Transmission:</td>
                <td><%= @listing.transmission %></td>
              </tr>
              <tr>
                <td class="vehicleSpecsName">Location:</td>
                <td><%= @listing.location %></td>

              </tr>
              <tr>
                <td class="vehicleSpecsName">Fuel Type:</td>
                <td><%= @listing.fuel_type %></td>
              </tr>
              <tr>
                <td class="vehicleSpecsName">Passengers:</td>
                <td><%= @listing.passengers %></td>
              </tr>
              <tr>
                <td class="vehicleSpecsName">Vehicle Length:</td>
                <td><%= @listing.vehicle_length %> feet</td>
              </tr>
              <tr>

                <td class="vehicleSpecsName">Exterior Color:</td>
                <td><%= @listing.exterior_color %></td>
              </tr>
              <tr>
                <td class="vehicleSpecsName">Interior Color:</td>
                <td><%= @listing.interior_color %></td>
              </tr>

              <tr>
                <td class="vehicleSpecsName">Luggage:</td>
                <td><%= @listing.luggage %></td>
              </tr>
              <tr>
                <td class="vehicleSpecsName">Wheelchair Lifts:</td>
                <td><%= @listing.wheelchair_lifts %></td>

              </tr>
              <tr>
                <td class="vehicleSpecsName">Warranty:</td>
                <td><%= @listing.warranty %></td>
              </tr>
            </table>
            <h4 class="customTitle4">Description</h4>
				<p><%= @listing.vehicle_description %></p>
           </div>
          <!-- gallery start -->
          <div class="gallery">
            <ul id="sliderOne">
              <% @listing.images.each do |bus| %>
              	<li class="slideModule"><%= image_tag bus.image_url, :height => "382", :width => "550", :id => "img1" %></li>
              <% end %>
              	<li class="slideModule"><img src="/assets/galleryImages/thumb1.jpg"  alt="" /></li>
            </ul>

            <!-- slider navigation start -->
            <div id="sliderNav">
              <ul id="sliderNavList">
              	<% @listing.images.each do |bus| %>
              		<li><a href="#"><%= image_tag bus.image_url(:thumb) , :height => "96", :width => "67" %></a></li>
              	<% end %>
                <!-- <li><a href="#"><img src="/assets/galleryImages/thumb1.jpg"  alt="" /></a></li>
                <li><a href="#"><img src="/assets/galleryImages/thumb1.jpg"  alt="" /></a></li>
                <li><a href="#"><img src="/assets/galleryImages/thumb1.jpg"  alt="" /></a></li> -->
              </ul>
            </div>
            <!-- slider navigation end -->
            <div class="galleryThumbsBottom"></div>
          </div>
          <!-- gallery end -->
        </div>
        <!-- table and gallery container end -->
      </div>

      <div class="detailedBoxLargeBottom"></div>
    </div>
    <!-- box end -->
    <!-- inquire start -->
    <div class="inquireContainer">
      <div class="inquireTop">
        <h4>Inquire About Stock Number: <%= @listing.stock_id %></h4>
      </div>
      
      <div class="inquireContent">
          <% unless notice.nil? %>
           		<p class="success"><%= notice %></p>
           	<% end %>
           	<% unless alert.nil? %>
           		<p class="alert"><%= alert %></p>
           	<% end %>
           	<% unless flash[:errors].nil? %>
           		<p class="alert">
           		   <% flash[:errors].each do |attr,m| %>
             		    <%= attr.to_s.titleize %>
             		    <%= m[0] %><br />
             		  <% end %>
           		</p>
           	<% end %>
          <fieldset> 
          	<%= form_for @lead, :url => new_lead_path, :method => "POST", :html => {:id => "inquire"} do |f| %>
            <div class="inquireFields">
                <%= f.label :first_name %><%= f.text_field :first_name, :class => "itext-input", :id => "inquireFName" %>
                
              	<%= f.label :last_name %><%= f.text_field :last_name, :class => "itext-input", :id => "inquireName" %>
				        <%= f.label :email %><%= f.text_field :email, :class => "itext-input", :id => "inquireName" %>
				        <%= f.label :phone, "Phone" %><%= f.text_field :phone, :class => "itext-input", :id => "inquireName" %>
				        <%= f.label :mobile, "Mobile" %><%= f.text_field :mobile, :class => "itext-input", :id => "inquireName" %>
				        <%= f.label :company, "Company Name" %><%= f.text_field :company, :class => "itext-input", :id => "inquireName" %>
                <%= f.label :address, "Address" %><%= f.text_field :address, :class => "itext-input", :id => "inquireName" %>
                <%= f.label :address2, "Address Line2" %><%= f.text_field :address2, :class => "itext-input", :id => "inquireName" %>              
                <%= f.label :unit, "Suite/Unit" %><%= f.text_field :unit, :class => "itext-input", :id => "inquireName" %>
                <%= f.label :city, "City" %><%= f.text_field :city, :class => "itext-input", :id => "inquireName" %>
                 <div>
                    <%= f.label :state, "Prov/State" %>
                    <%= f.grouped_collection_select :state, Country.order(:name), :states, :name, :name, :name, :class => "itext-input", :id => "inquireName", include_blank: true %>
                    </div>
                <%= f.label :country, "Country" %><%= f.collection_select :country, Country.order(:name), :name, :name, :class => "itext-input", :id => "inquireName", include_blank: true %>
               
                <%= f.label :postal, "Postal/Zip" %><%= f.text_field :postal, :class => "itext-input", :id => "inquireName" %>      
            </div>
            		<%= f.label :comments, "Comments or Questions:" %>
            		<%= f.text_area :comments, :class => "itext-input", :id => "inquireMessage", :rows => "2", :cols => "1"%>
            		<%= f.hidden_field :bus_id, :value => @listing.id %>
            <p>
            		<%= f.submit "", :class => "inquireButton", :id => "inquireSubmitBtn" %>
            </p>
            <% end %>
          </fieldset>
      </div>
      <div class="inquireBottom"></div>
    </div>
    <!-- inquire end -->

  </div>
</div>
<!-- page end -->
<%= render :partial => 'shared/compare_toolbar'   %>

app/views/listings/show.html.haml
/ bus name and price starts
#detail_titlearea
  .detail_headings
    .detail_heading_left
      %h1
        = @listing.year
        = @listing.body_make.name
        = @listing.body_model
      %h2
        = number_to_currency(@listing.price_on_site, :precision => 0)
        %span.currncy-two
          = @listing.location == "USA" ? "USD" : "CDN"
    %h3
      Stock Number: #{@listing.stock_id}
  .detail_heading_right
    %a.back_btn{:href => "index.html"} Back to Inventory
    %a.print_btn{:href => "", :onclick => "window.print();return false;"} Print
/ bus name and price ends
#detail_content
  / inventory details start
  #detail_specs_area
    / slider gallery start
    #Slider_container
      .gallery
        %ul#sliderOne
          - @listing.images.each do |bus|
            %li.slideModule= image_tag bus.image_url, :height => "415", :width => "625", :id => "img1"
        / slider navigation start
        #sliderNav
          %ul#sliderNavList
            - @listing.images.each do |bus|
              %li
                %a{:href => "#"}= image_tag bus.image_url(:thumb) , :height => "96", :width => "67"
        / slider navigation end
    / silder gallery ends
    / Vehicle specs start
    .detail_specs_panel
      %h4.vehicle_specs_title Specifications
      .vehicleInfo
        %table.vehicleSpecs{:width => "432"}
          %tr
            %td.vehicleSpecsName{:width => "97"} Year:
            %td{:width => "319"}
              =@listing.year
          %tr
            %td.vehicleSpecsName Bus Type:
            %td
              =@listing.bus_type.name
          %tr
            %td.vehicleSpecsName Chassis Make:
            %td
              =@listing.chasis_make.name
          %tr
            %td.vehicleSpecsName Chassis Model:
            %td
              = @listing.chasis_model
          %tr
            %td.vehicleSpecsName Body Make:
            %td
              = @listing.body_make.name
          %tr
            %td.vehicleSpecsName Body Model:
            %td
              = @listing.body_model
          %tr
            %td.vehicleSpecsName Engine:
            %td
              = @listing.engine
          %tr
            %td.vehicleSpecsName Mileage:
            %td
              = (number_with_delimiter @listing.mileage.to_i).to_s + " kms"
          %tr
            %td.vehicleSpecsName Transmission:
            %td
              = @listing.transmission
        %table.vehicleSpecs{:width => "200"}
          %tr
            %td.vehicleSpecsName{:width => "94"} Location:
            %td{:width => "94"}
              = @listing.location
          %tr
            %td.vehicleSpecsName State:
            %td
              = @listing.state.name unless @listing.state.blank?
          %tr
            %td.vehicleSpecsName Fuel Type:
            %td
              = @listing.fuel_type
          %tr
            %td.vehicleSpecsName Passengers:
            %td
              = @listing.passengers
          %tr
            %td.vehicleSpecsName Vehicle Length:
            %td
              = @listing.vehicle_length
          %tr
            %td.vehicleSpecsName Exterior Color:
            %td
              = @listing.exterior_color
          %tr
            %td.vehicleSpecsName Interior Color:
            %td
              = @listing.interior_color
          %tr
            %td.vehicleSpecsName Luggage:
            %td
              = @listing.luggage
          %tr
            %td.vehicleSpecsName Wheelchair Lift:
            %td
              = @listing.wheelchair_lifts
          %tr
            %td.vehicleSpecsName Warranty:
            %td
              = @listing.warranty
    / vehicle specs end
    .detail_specs_panel
      %h4.vehicle_specs_title Description
      %p.vehicle_description_text
        = @listing.vehicle_description
  / inventory details ends
  / right ads start
  #detail_right_panel
    #inquire_container
      %span.inquire_title
        Inquire Now or
        %span.bold_text Call Us at 1-888-679-0088
      #inquire_form
        = form_for :user , :url => send_inquiry_received_email_listings_path, :method => :post , :html => { :id => 'inquire' }  do |f|
          %p#error-form-inquire
          = hidden_field_tag "back_to", @listing.stock_id
          %p Your Name:
          %input#inquirename{:name => "inquirename", :tabindex => "1", :type => "text"}/
          %br/
          %br/
          %p Your Email:
          %input#inquiremail{:name => "inquiremail", :tabindex => "2", :type => "text"}/
          %br/
          %br/
          %p Comments:
          %textarea#comments{:cols => "45", :name => "comments", :rows => "5", :tabindex => "3"}
      #inquire_form_btns
        %a.send_inquiry_btn{:href => "javascript:", :id => "inquire_submit"} Send Inquiry
        %a.send_friend_btn{:href => "#" , :id => "create-user"} Send to a Friend
    / more buses starts
    #more_buses_panel
      %span.more_bus_title More Buses
      -@related_buses.each do |bus|
        -unless bus.id == @listing.id
          .more_bus_item
            %a.more_bus_thumb_btn{:href => "/listings/#{bus.stock_id}"}
              =image_tag bus.images.first.image_url(:thumb) , :height => "75", :width => "100"
            %h3
              %a.more_bus_btn{:href => "/listings/#{bus.stock_id}"}
                = bus.year
                = bus.body_model
            %span.more_bus_price
              = number_to_currency(bus.price_on_site, :precision => 0)
              %span.currency CDN
        / more bus item ends
    / more buses ends
  / right ads end
/ listing content ends
.clearfooter

= render :partial => "send_friend"