config/routes.rb
Buscms::Application.routes.draw do

  get "admin/export/to_xls", :as => :export_to_xls
  get "admin/export/to_pdf", :as => :export_to_pdf

  devise_for :admins
  devise_for :dealers, :controllers => {:confirmations => "confirmations"}
  devise_for :users

  match 'admin/bus_type' => 'admin/bus_types#create', :via => [:post, :put]
  match 'admin/chasis_makes' => 'admin/chasis_makes#create', :via => [:post, :put]
  match 'admin/images' => 'admin/images#create', :via => [:post, :put]
  match 'admin/inventory/search' => 'admin/inventory#search', :via => [:get, :post]
  match 'admin/inventory/update_status' => 'admin/inventory#update_status', :via => [:get, :post]
  match 'admin/leads/search_leads' => 'admin/leads#search_leads', :via => [:get, :post]
  match 'admin/export/to_xls' => 'admin/export#to_xls', :via => [:get, :post]
  match 'admin/export/to_xls_leads' => 'admin/export#to_xls_leads', :via => [:get, :post]
  match 'admin/export/to_pdf' => 'admin/export#to_pdf', :via => [:get, :post]
  match 'admin/export/to_pdf_multiple' => 'admin/export#to_pdf_multiple', :via => [:get, :post]
  match 'admin/export/to_pdf_multiple_leads' => 'admin/export#to_pdf_multiple_leads', :via => [:get, :post]
  match 'admin/export/destroy' => 'admin/inventory#destroy', :via => [:get], :as => :delete_inventory
  match 'admin/dealers/destroy' => 'admin/dealers#destroy', :via => [:get], :as => :delete_dealers
  match 'admin/users/destroy' => 'admin/users#destroy', :via => [:get], :as => :delete_users
  match 'admin/leads/destroy' => 'admin/leads#destroy', :via => [:get], :as => :delete_leads
  match 'admin/export/to_zip' => 'admin/export#to_zip', :via => [:get], :as => :zip_inventory
  match 'addtocompare' => 'home#addtocompare', :via => [:get], :as => :add_to_compare
  match 'removefromcompare' => 'home#removefromcompare', :via => [:get], :as => :remove_from_compare
  match 'admin/adds/delete_bulk_ads' => 'admin/adds#delete_bulk_ads', :via => [:get], :as => :remove_from_add
  match 'admin/adds/filter' => 'admin/adds#filter', :via => [:get], :as => :filter_add
  match '/generate_stock_id' => 'home#generate_stock_id', :via => [:get], :as => :generate_stock_id

  namespace :admin do
    resources :users
    match 'users/confirm_user_account/:id' => 'users#confirm_account', :via => [:get], :as => :confirm_user_account
    match 'dealers/confirm_dealer_account/:id' => 'dealers#confirm_account', :via => [:get], :as => :confirm_dealer_account
    match 'users/deactivate_account/:id' => 'users#deactivate_account', :via => [:get], :as => :deactivate_account
    match 'settings/update_settings' => 'settings#update_settings'
    match 'leads/send_email' => 'leads#send_email', :via => :post
    match 'leads/create_blast' => 'leads#create_blast', :via => :get
    match 'leads/remove_stock_session' => 'leads#remove_stock_session', :via => :get
    match 'leads/add_stock' => 'leads#add_stock', :via => :get
    match 'leads/blast_step3' => 'leads#blast_step3', :via => :get
    match 'leads/blast_last_step' => 'leads#blast_last_step', :via => :post
    match 'leads/send_blast' => 'leads#send_blast', :via => :post
    match 'leads/search' => 'leads#search'

    match 'search' => 'search#index'
    match 'recyclebins/restore' => 'recyclebins#restore'
    match 'recyclebins/restore_all' => 'recyclebins#restore_all'
    match 'recyclebins/restore_all_current_bin' => 'recyclebins#restore_all_current_bin'
    match 'recyclebins/empty_all' => 'recyclebins#empty_all'
    match 'recyclebins/empty_bin' => 'recyclebins#empty_bin'
    match 'recyclebins/set_delete_timer' => 'recyclebins#set_delete_timer'

    resources :images #, :only => [:index, :create, :destroy]
    resources :bus_type
    resources :inventory

    resources :contact
    resources :sold_inventory
    resources :settings
    resources :leads
    resources :chasis_makes
    resources :body_makes
    resources :dealers
    resources :stats
    resources :recyclebins
    resources :adds 
  end
  match 'listings/compare' => 'listings#compare', :via => :get
  match 'listings/search' => 'listings#search'
  match 'listings/:slug' => 'listings#index', :via => :get, :as => :buses_search, :slug => /[a-z-]{0,}/
  match 'contact/new_lead' => 'contact#new_lead', :via => [:post], :as => :new_lead

  resources :contact
  resources :listings, :only => [:show, :index, :search , :send_mail_to_friend, :send_inquiry_received_email] do
    collection do
      match 'search' => 'listings#search', :via => :get, :as => :search
      post 'send_friend_mail' => 'listings#send_mail_to_friend'
      post 'send_inquiry_received_email' => 'listings#send_inquiry_received_email'
    end
  end
  resources :dealer

  match 'cron/cron_to_update_bus_stats' => 'home#cron_to_update_bus_stats'
  match "/admin", :to => redirect("/admin/dashboard")
  match 'admin/dashboard' => 'admin/dashboard#index', :via => [:get, :post], :as => :admin_dashboard
  match 'services' => 'home#services', :as => :services
  match 'about' => 'home#about', :as => :about
  match 'contact' => 'contact#index', :as => :contact
  match 'submit_vehicle' => 'home#submit_vehicle', :as => :submit_vehicle
  match 'dealer' => 'dealer#index', :as => :dealer
  match 'add_new_vehicle' => 'home#add_new_vehicle', :as => :add_new_vehicle
  match 'compare' => 'home#compare', :as => :compare
  match 'temp' => 'temp_uploader#upload' , :as => :temp
  match '/admin/adds/update' => 'admin/adds#update'

  root :to => 'listings#index'

end

app/views/shared/recyclinbin/_dealers_recyclinbin.html.erb
<% if @dealers.blank? %>
	<tr><td><h2>Currently there are no items in Dealers bin</h2></td></tr>
<% else %>
<thead>
  <%= render 'shared/recyclinbin/tableHeader_recyclinbin', binMenu: @binMenu[3] %>
	<tr>
		<th class="unsortable" style="border-left:1px solid #cdcdcd; width: 1%;"></th>
		<th class="actions_col unsortable" width="140px"><a href="#">Actions</a></th>
    <th><%= sortable "first_name" %></th>
    <th><%= sortable "last_name" %></th>
    <th><%= sortable "email" %></th>
    <th><%= sortable "created_at" %></th>
    <th><%= sortable "updated_at" %></th>
    <th><%= sortable "sign_in_count" %></th>
    <th><%= sortable "last_sign_in_at" %></th>
		<th><%= sortable 'deleted_at',"Date Deleted" %></th>
	</tr>
</thead>
<!-- Table row classes : gray, nothing, selected   -->
<tbody>
	<% @dealers.each do |dealer| %>  
		<tr class="bus_row">
			<td><input class="recycle_check_box" name="select" type="checkbox" value="<%= dealer.id %>" data-stock-id="<%= dealer.id %>"/></td>
      <td class="actions"><%= permanent_delete(dealer,'dealers') %></td>
      <td><%= dealer.first_name %></td>
      <td><%= dealer.last_name %></td>
      <td><%= dealer.email %></td>
      <td><%= dealer.created_at.to_app_date %></td>
      <td><%= dealer.updated_at.to_app_date %></td>
      <td><%= dealer.sign_in_count %></td>
      <td><%= dealer.last_sign_in_at.to_app_date if dealer.last_sign_in_at %></td>
			<td><%= print_date(dealer.deleted_at) %></td>

		</tr>
	<% end %>
</tbody>
<% end %>

app/views/shared/recyclinbin/_inventory_recyclinbin.html.erb
<% if inventory.blank? %>
	<tr><td><h2>Currently there are no items in Inventory bin</h2></td></tr>
<% else %>

<thead>
  <%= render 'shared/recyclinbin/tableHeader_recyclinbin', sold ? {binMenu: @binMenu[1]}: {binMenu: @binMenu[0]} %>
	<tr>
		<th class="unsortable" style="border-left:1px solid #cdcdcd; width: 1%;"></th>
		<th class="actions_col unsortable" width="8%"><a href="#">Actions</a></th>
		<th><%= sortable "stock_id","Stock ID" %></th>
		<th><%= sortable "status" %></th>
		<th>Bus Type</th>
		<th><%= sortable "year" %></th>
		<th>Chasis Make</th>
		<th><%= sortable "chasis_model" %></th>
		<th><%= sortable "fuel_type" %></th>
		<th><%= sortable "mileage","KMS" %></th>
		<th><%= sortable "passengers","Seats" %></th>
		<th><%= sortable 'created_at',"Added" %></th>
		<th><%= sortable "price" %></th>
		<th>Hits</th>
		<th><%= sortable 'deleted_at',"Date Deleted" %></th>
	</tr>
</thead>
<!-- Table row classes : gray, nothing, selected   -->
<tbody>
	<% inventory.each do |inv| %>  
	<tr class="bus_row">
		<td><input class="recycle_check_box" name="select" type="checkbox" value="<%= inv.id %>" data-stock-id="<%= inv.id %>"/></td>
		<td>
			<%= link_to image_tag("/assets/admin/icons/action1.png"), '#', :alt => "Vehicle Preview", :id => inv.stock_id, :'data-hover-image' => "<img src=#{inv.images.first.image_url(:thumb)} >", :class => "bus_camera"%>
				<%= permanent_delete(inv,'inventory') %>
		</td>
		<td><%= inv.stock_id %></td>
		<td><%= image_as_status(inv.status) %></td><%# HELPER METHOD recyclinbin  %>
		<td><%= inv.bus_type.name%></td>
		<td><%= inv.year %></td>
		<td><%= inv.chasis_make.name %></td>
		<td><%= inv.chasis_model %></td>
		<td><%= inv.fuel_type %></td>
		<td><%= inv.mileage %></td>
		<td><%= inv.passengers %></td>
		<td><%= print_date(inv.created_at) %></td>
		<td><%= number_to_currency( inv.price ) %></td>
		<td><%= inv.hits %></td>
		<td><%= print_date(inv.deleted_at) %></td>
	</tr>
	<%end%>
</tbody>
<%end%>

app/views/shared/recyclinbin/_leads_recyclinbin.html.erb
<% if @leads.blank? %>
	<tr><td><h2>Currently there are no items in Leads bin</h2></td></tr>
<% else %>
<thead>
  <%= render 'shared/recyclinbin/tableHeader_recyclinbin', binMenu: @binMenu[2] %>
	<tr>
		<th class="unsortable" style="border-left:1px solid #cdcdcd; width: 1%;"></th>
		<th class="actions_col unsortable" width="140px"><a href="#">Actions</a></th>
    <th><%= sortable "first_name" %></th>
    <th><%= sortable "last_name" %></th>
    <th><%= sortable "email" %></th>
    <th><%= sortable "company" %></th>
    <th><%= sortable "country" %></th>
    <th><%= sortable "province" %></th>
    <th><%= sortable "city" %></th>
    <th><%= sortable "created_at" %></th>
		<th><%= sortable 'deleted_at',"Date Deleted" %></th>
	</tr>
</thead>
<!-- Table row classes : gray, nothing, selected   -->
<tbody>
	<% @leads.each do |lead| %>  
  	<tr class="bus_row">
      <td><input class="recycle_check_box" name="select" type="checkbox" value="<%= lead.id %>" /></td>
      <td class="actions"><%= permanent_delete(lead, 'leads') %></td>
      <td><%= lead.first_name %></td>
      <td><%= lead.last_name %></td>
      <td><%= lead.email %></td>
      <td><%= lead.company %></td>
      <td><%= lead.country %></td>
      <td><%= lead.province %></td>
      <td><%= lead.city %></td>
      <td><%= lead.created_at.to_app_date %></td>
			<td><%= print_date(lead.deleted_at) %></td>

		</tr>
	<% end %>
</tbody>
<% end %>

app/views/shared/recyclinbin/_menu_icons_recyclinbin.html.erb
<div class="contentMenu recyclebin">
  <div class="clear"></div>
  <div class="contentCaption" style='height:30px'><%= image_tag "/assets/admin/icons/recycle.png"%>Recyclin Bin</div>
  <div class="menuIcons">

    <div class="menuIcon">
      <%= link_to image_tag("/assets/admin/icons/recyclinbin.png", :alt => "Empty All"), admin_recyclebins_empty_all_path, confirm: 'Do you really want to empty the Recycle Bin?' %><br/>Empty All
    </div>

    <div class="menuIcon">
      <%= link_to image_tag("/assets/admin/icons/restore.png", :alt => "Restore All"), admin_recyclebins_restore_all_path, confirm: 'Are You Sure!' %><br/>Restore All
    </div>
    <div class="clear"></div>
  </div>

  <script type="text/javascript">

    $(document).ready(function(){
      $('.noOfDaysForm form').submit(function(){
        if (confirm('Are You Sure!')) {
          timer = $(this).find('select').val();
          location.href = '<%= admin_recyclebins_set_delete_timer_path %>?bin=<%= params[:bin] %>&timer='+timer;
        };
        return false;
      });
    });
  </script>

  <div class='noOfDaysForm'>
    <span>Items are set to be deleted after</span>
    <%= form_tag admin_recyclebins_set_delete_timer_path %>
    <select name="timer">
      <%if Settings.find_by_setting_type("Delete")%>
        <% bin_delete = Settings.get('Delete')[params[:bin]] %>
        <% [1,3,15,30,60,90].each do |d| %>
          <option value=<%= d %> <%= ' selected' if bin_delete.to_s == d.to_s %> ><%= pluralize(d,'day') %></option>
        <%end %>
      <%end %>
    </select>
    <%= submit_tag 'Save Changes'%>
  </div>

  <div class="clear"></div>
</div>

app/views/shared/recyclinbin/_tableHeader_recyclinbin.html.erb
<script type="text/javascript">	
	function get_selected_checkBoxes() {
		var data = $('input:checkbox:checked.recycle_check_box').map(function () {
	   		return this.value;
		}).get();
		return data;		
	}

	function submit_restore() {
		var data = get_selected_checkBoxes();
		if (data.length == 0) {
			alert('No checkbox selected!');
			return false;
		} else if(confirm("Are you sure you want to restore these records?")){	
			location.href = '<%= admin_recyclebins_restore_path %>?ids=['+data+']&bin=<%= params[:bin] %>';
		}
	}
</script>

<tr class="tableTop">
	<td colspan="15">
		<div class="tableTopHeader">
			<span><%= binMenu %></span>
			<script>$('.tableTopHeader span a').addClass('theadNoOfItems')</script>
			<div class='restoreButtons'>
				<a href="#" onclick="submit_restore()" >Restore</a>
				<%= link_to 'Restore All', admin_recyclebins_restore_all_current_bin_path+"?bin=#{params[:bin]}", confirm: 'Are You Sure!' %>
				<%= link_to 'Empty Folder', admin_recyclebins_empty_bin_path+"?bin=#{params[:bin]}", confirm: 'Are You Sure!' %>
			</div>

			<div class="clear"></div>
		</div>
		<div class="headerDivider"></div>
	</td>
</tr>
<tr><td style="position: absolute;"><input id="select1" name="select" type="checkbox"/></td></tr>

app/views/shared/recyclinbin/_users_recyclinbin.html.erb
<% if @users.blank? %>
	<tr><td><h2>Currently there are no items in Users bin</h2></td></tr>
<% else %>
<thead>
  <%= render 'shared/recyclinbin/tableHeader_recyclinbin', binMenu: @binMenu[4] %>
	<tr>
		<th class="unsortable" style="border-left:1px solid #cdcdcd; width: 1%;"></th>
		<th class="actions_col unsortable" width="140px"><a href="#">Actions</a></th>
		<th><%= sortable "first_name" %></th>
		<th><%= sortable "last_name" %></th>
		<th><%= sortable "email" %></th>
		<th><%= sortable "created_at" %></th>
		<th><%= sortable "updated_at" %></th>
		<th><%= sortable "sign_in_count" %></th>
		<th><%= sortable "confirmed_at","confirmed" %></th>
		<th><%= sortable "last_sign_in_at" %></th>
		<th><%= sortable 'deleted_at',"Date Deleted" %></th>
	</tr>
</thead>
<!-- Table row classes : gray, nothing, selected   -->
<tbody>
	<% @users.each do |user| %>  
		<tr class="bus_row">
			<td><input class="recycle_check_box" name="select" type="checkbox" value="<%= user.id %>" data-stock-id="<%= user.id %>"/></td>
			<td class="actions"><%= permanent_delete(user,'users') %></td>
			<td><%= user.first_name %></td>
			<td><%= user.last_name %></td>
			<td><%= user.email %></td>
			<td><%= user.created_at.to_app_date %></td>
			<td><%= user.updated_at.to_app_date %></td>
			<td><%= user.sign_in_count %></td>
			<td><%= user.confirmed_at ? "Yes" : "No" %></td>
			<td><%= user.last_sign_in_at.to_app_date if user.last_sign_in_at.present? %></td>
			<td><%= print_date(user.deleted_at) %></td>

		</tr>
	<% end %>
</tbody>
<% end %>