config/routes.rb
Buscms::Application.routes.draw do

  get "admin/export/to_xls", :as => :export_to_xls
  get "admin/export/to_pdf", :as => :export_to_pdf

  devise_for :admins
  devise_for :dealers, :controllers => {:confirmations => "confirmations"}
  devise_for :users

  match 'admin/bus_type' => 'admin/bus_types#create', :via => [:post, :put]
  match 'admin/chasis_makes' => 'admin/chasis_makes#create', :via => [:post, :put]
  match 'admin/images' => 'admin/images#create', :via => [:post, :put]
  match 'admin/inventory/search' => 'admin/inventory#search', :via => [:get, :post]
  match 'admin/inventory/update_status' => 'admin/inventory#update_status', :via => [:get, :post]
  match 'admin/leads/search_leads' => 'admin/leads#search_leads', :via => [:get, :post]
  match 'admin/export/to_xls' => 'admin/export#to_xls', :via => [:get, :post]
  match 'admin/export/to_xls_leads' => 'admin/export#to_xls_leads', :via => [:get, :post]
  match 'admin/export/to_pdf' => 'admin/export#to_pdf', :via => [:get, :post]
  match 'admin/export/to_pdf_multiple' => 'admin/export#to_pdf_multiple', :via => [:get, :post]
  match 'admin/export/to_pdf_multiple_leads' => 'admin/export#to_pdf_multiple_leads', :via => [:get, :post]
  match 'admin/export/destroy' => 'admin/inventory#destroy', :via => [:get], :as => :delete_inventory
  match 'admin/dealers/destroy' => 'admin/dealers#destroy', :via => [:get], :as => :delete_dealers
  match 'admin/users/destroy' => 'admin/users#destroy', :via => [:get], :as => :delete_users
  match 'admin/leads/destroy' => 'admin/leads#destroy', :via => [:get], :as => :delete_leads
  match 'admin/export/to_zip' => 'admin/export#to_zip', :via => [:get], :as => :zip_inventory
  match 'addtocompare' => 'home#addtocompare', :via => [:get], :as => :add_to_compare
  match 'removefromcompare' => 'home#removefromcompare', :via => [:get], :as => :remove_from_compare
  match 'admin/adds/delete_bulk_ads' => 'admin/adds#delete_bulk_ads', :via => [:get], :as => :remove_from_add
  match 'admin/adds/filter' => 'admin/adds#filter', :via => [:get], :as => :filter_add
  match '/generate_stock_id' => 'home#generate_stock_id', :via => [:get], :as => :generate_stock_id

  namespace :admin do
    resources :users
    match 'users/confirm_user_account/:id' => 'users#confirm_account', :via => [:get], :as => :confirm_user_account
    match 'dealers/confirm_dealer_account/:id' => 'dealers#confirm_account', :via => [:get], :as => :confirm_dealer_account
    match 'users/deactivate_account/:id' => 'users#deactivate_account', :via => [:get], :as => :deactivate_account
    match 'settings/update_settings' => 'settings#update_settings'
    match 'leads/send_email' => 'leads#send_email', :via => :post
    match 'leads/create_blast' => 'leads#create_blast', :via => :get
    match 'leads/remove_stock_session' => 'leads#remove_stock_session', :via => :get
    match 'leads/add_stock' => 'leads#add_stock', :via => :get
    match 'leads/blast_step3' => 'leads#blast_step3', :via => :get
    match 'leads/blast_last_step' => 'leads#blast_last_step', :via => :post
    match 'leads/send_blast' => 'leads#send_blast', :via => :post
    match 'leads/search' => 'leads#search'

    match 'search' => 'search#index'
    match 'recyclebins/restore' => 'recyclebins#restore'
    match 'recyclebins/restore_all' => 'recyclebins#restore_all'
    match 'recyclebins/restore_all_current_bin' => 'recyclebins#restore_all_current_bin'
    match 'recyclebins/empty_all' => 'recyclebins#empty_all'
    match 'recyclebins/empty_bin' => 'recyclebins#empty_bin'
    match 'recyclebins/set_delete_timer' => 'recyclebins#set_delete_timer'

    resources :images #, :only => [:index, :create, :destroy]
    resources :bus_type
    resources :inventory

    resources :contact
    resources :sold_inventory
    resources :settings
    resources :leads
    resources :chasis_makes
    resources :body_makes
    resources :dealers
    resources :stats
    resources :recyclebins
    resources :adds 
  end
  match 'listings/compare' => 'listings#compare', :via => :get
  match 'listings/search' => 'listings#search'
  match 'listings/:slug' => 'listings#index', :via => :get, :as => :buses_search, :slug => /[a-z-]{0,}/
  match 'contact/new_lead' => 'contact#new_lead', :via => [:post], :as => :new_lead

  resources :contact
  resources :listings, :only => [:show, :index, :search , :send_mail_to_friend, :send_inquiry_received_email] do
    collection do
      match 'search' => 'listings#search', :via => :get, :as => :search
      post 'send_friend_mail' => 'listings#send_mail_to_friend'
      post 'send_inquiry_received_email' => 'listings#send_inquiry_received_email'
    end
  end
  resources :dealer

  match 'cron/cron_to_update_bus_stats' => 'home#cron_to_update_bus_stats'
  match "/admin", :to => redirect("/admin/dashboard")
  match 'admin/dashboard' => 'admin/dashboard#index', :via => [:get, :post], :as => :admin_dashboard
  match 'services' => 'home#services', :as => :services
  match 'about' => 'home#about', :as => :about
  match 'contact' => 'contact#index', :as => :contact
  match 'submit_vehicle' => 'home#submit_vehicle', :as => :submit_vehicle
  match 'dealer' => 'dealer#index', :as => :dealer
  match 'add_new_vehicle' => 'home#add_new_vehicle', :as => :add_new_vehicle
  match 'compare' => 'home#compare', :as => :compare
  match 'temp' => 'temp_uploader#upload' , :as => :temp
  match '/admin/adds/update' => 'admin/adds#update'

  root :to => 'listings#index'

end

app/views/shared/_admin_header.html.erb
<div id="header">
		<!--[if lte IE 9]>
			<script  src="/js/jquery.corner.js"></script>
			<script>
		 		$(".topMenu ul li a").corner("cc:#414141 top 10px");
		 		$(".contentCaption").corner("round 10px");
		 	</script>
		<![endif]-->
	 	
		<%= link_to "<span class='logo'></span>".html_safe, admin_dashboard_path %>
        <div class="login">
            <img src="/assets/admin/icons/user.png" alt="User Picture"/> Hello <strong><%= login_greet %></strong>
			| <strong><%= link_to "Logout", user_session_destroy_path %></strong>
        </div>
        <div class="search">
            <form action="/admin/search" method="get">
                <div class="searchIcon"></div>
                <select name="search_in">
                    <option value="inventory">Inventory</option>
                    <option value="leads">Leads</option>
                </select>
                <div class="searchLeft"></div>
                <input type="text" id="search" name="query" placeholder="stock id, first name, last name etc.." value = "<%= params[:query] if params[:query] %>" >
                <input type="submit" id="searchSubmit" name="searchSubmit" value=""/><br />
            </form>
        </div>
        
        <div class="topMenu">
            <ul>
                <li><%= link_to "Dashboard", admin_dashboard_path, :class => active_link?("/admin/dashboard") %></li>
                <li><%= link_to "User Manager", admin_users_path, :class => active_link?("/admin/users") if admin_signed_in? %></li>
                <li><%= link_to "Inventory Manager", admin_inventory_index_path(:per_page => 10), :class => active_link?("/admin/inventory") %></li>
                <li><%= link_to "Sold Manager", admin_sold_inventory_index_path, :class => active_link?("/admin/sold_inventory") if admin_signed_in? %></li>
                <li><%= link_to "Lead Manager", admin_leads_path, :class => active_link?("admin/leads") %></li>
                <li><%= link_to "Dealer Manager", admin_dealers_path, :class => active_link?("/admin/dealers")  %></li>
                <li><%= link_to "Ad Manager", admin_adds_path, :class => active_link?("/admin/adds") %></li>
                <li><%= link_to "Settings", admin_settings_path, :class => active_link?("/admin/settings") %></li>
                <li><%= link_to "Contact Us Forms", admin_contact_index_path, :class => active_link?("/admin/contact") %></li>
            </ul>

        </div>
        <div class='recyclinBin'>
            <%= link_to "Recyclin Bin", admin_recyclebins_path+"?bin=inventory", :class => active_link?("/admin/recyclebins") %>
        </div>
	</div><!-- #header-->

app/views/shared/_backend_filter.html.erb
<% if params[:action] == "create_blast" or params[:controller] == "admin/leads" %>
    <%= form_tag('/admin/leads/search', :method => :get, :style => "float: left;") do %>
        <%= select("search", "bus_type_id", BusType.all.collect { |b| [b.name, b.id] }, {:include_blank => "Bus Type"}) %>
        <%= select("search", "chasis_make_id", ChasisMake.all.collect { |c| [c.name, c.id] }, {:include_blank => "Chasis Make"}) %>
        <%= select("search", "location", ["USA", "Canada"], {:include_blank => "Location"}) %>
        <%= select("search", "passengers", (0..100).step(10).to_a.map { |n| ["#{n+1} - #{n+10}", n] }, {:include_blank => "Passenger Seats"}) %>
        <%= select("search", "featured", ["yes", "no"], {:include_blank => "Featured"}) %>
        <%= select("search", "status", Bus::STATUSES.collect { |s| [s[:string].capitalize, s[:string]] }, {:include_blank => "Status"}) %>
        <%= select("search", "live", ["Yes", "No"], {:include_blank => "Live"}) %>
        <%= datepicker_input "search", "from", :maxDate => "+1D", :minDate => Bus.first.created_at.to_date - Date.today %>
        To > <%= datepicker_input "search", "to", :maxDate => "+1D", :minDate => Bus.first.created_at.to_date - Date.today %>
        <% if params[:controller] == "admin/sold_inventory" %>
            <%= hidden_field_tag "search[sold]", "1" %>
        <% end %>
        <%= submit_tag "Filter" %>
    <% end %>
<% else %>
    <%= form_tag('/admin/inventory/search', :method => :get, :style => "float: left;") do %>
        <%= select("search", "bus_type_id", BusType.all.collect { |b| [b.name, b.id] }, {:include_blank => "Bus Type"}) %>
        <%= select("search", "chasis_make_id", ChasisMake.all.collect { |c| [c.name, c.id] }, {:include_blank => "Chasis Make"}) %>
        <%= select("search", "location", ["USA", "Canada"], {:include_blank => "Country"}) %>
        <%= select "search","state_empty_admin" ,State.where("country_id = ? ",Country.find_by_name("")), {:include_blank => "State (any)"} %>
        <%= select "search", "state_usa_admin", State.where("country_id = ? ", Country.find_by_name("United States").id).collect { |c| [c.name, c.id] }, {:include_blank => "State (any)"} %>
        <%= select "search", "state_canada_admin",State.where("country_id = ? ", Country.find_by_name("Canada").id).collect { |c| [c.name, c.id] }, {:include_blank => "State (any)", :id => "state_canada", :tabindex => "2", :class => "state", :style => "display: none" }%>
        <%= select("search", "passengers", (0..100).step(10).to_a.map { |n| ["#{n+1} - #{n+10}", n] }, {:include_blank => "Passenger Seats"}) %>
        <%= select("search", "featured", ["yes", "no"], {:include_blank => "Featured"}) %>
        <%= select("search", "status", Bus::STATUSES.collect { |s| [s[:string].capitalize, s[:string]] }, {:include_blank => "Status"}) %>
        <%= select("search", "live", ["Yes", "No"], {:include_blank => "Live"}) %>
        <%= datepicker_input "search", "from", :maxDate => "+1D", :minDate => Bus.first.created_at.to_date - Date.today %>
        To > <%= datepicker_input "search", "to", :maxDate => "+1D", :minDate => Bus.first.created_at.to_date - Date.today %>
        <% if params[:controller] == "admin/sold_inventory" %>
            <%= hidden_field_tag "search[sold]", "1" %>
        <% end %>
        <%= submit_tag "Filter" %>
    <% end %>
<% end %>

app/views/shared/_backend_filter_leads.html.erb
	<%= form_tag('/admin/leads/search_leads', :method => :get, :style => "float: left;") do %>
		<%= select("search", "country", Lead.where("country != ?", "").collect {|b| [ b.country, b.country ] if b.country }.uniq, { :include_blank => "Country" }) %>
		<%= select("search", "province", Lead.where("province != ?", "").collect {|b| [ b.province, b.province ] if b.province }.uniq, { :include_blank => "Province" }) %>
		<%= select("search", "city", Lead.where("city != ?", "").collect {|b| [ b.city, b.city ] if b.city }.uniq, { :include_blank => "City" }) %>
		<%= select("search", "company", Lead.where("company != ?", "").collect {|b| [ b.company, b.company ] }.uniq, { :include_blank => "Company Name" }) %>
		<%= datepicker_input "search","from", :maxDate => "+1D", :minDate => Lead.first.created_at.to_date - Date.today %> 
		To > <%= datepicker_input "search","to", :maxDate => "+1D", :minDate => Lead.first.created_at.to_date - Date.today  %>
		<%= submit_tag "Filter" %>
	<% end %>

app/views/shared/_compare_toolbar.html.erb
<%= hidden_field_tag 'count_value', @compare_list.count %>
<script>
    function submit_add_to_compare(id, obj_e) {
        count_v = $('#count_value').val();
        if ($(obj_e).is(':checked')) {
            if (parseInt(count_v) + 1 >= 6) {
                alert("You may select up to 6 items to compare at one time");
                $(obj_e).attr('checked', false);
            } else {
                alert("You have successfully added the bus.");
                $.ajax({
                    url: '<%= add_to_compare_path %>?bus_type_id=<%=params[:bus_type_id] %>&id=' + id,
                    type: 'get',
                    dataType: 'html',
                    processData: false,
                    success: function (data) {
                        $('#compare-added-buses').html(data);
                        count = parseInt(count_v) + 1;
                        $('#count_value').val(count);
                    }
                });
            }
        }
        else {
            count_v = $('#count_value').val();
            if (parseInt(count_v) - 1 >= 6) {
                alert("You may select up to 6 items to compare at one time");
                $(obj_e).attr('checked', false);
            } else {
                alert("You have successfully removed the bus from compare list.");
                $.ajax({
                    url: '<%= remove_from_compare_path %>?bus_type_id=<%=params[:bus_type_id] %>&id=' + id,
                    type: 'get',
                    dataType: 'html',
                    processData: false,
                    success: function (data) {
                        $('#compare-added-buses').html(data);
                        count = parseInt(count_v) - 1;
                        $('#count_value').val(count);
                    }
                });
            }
        }

    }
    function submit_remove_from_compare(id, obj_e) {
        count_v = $('#count_value').val();
        if (parseInt(count_v) - 1 >= 6) {
            alert("You may select up to 6 items to compare at one time");
            $(obj_e).attr('checked', false);
        } else {
            alert("You have successfully removed the bus from compare list.")
            $.ajax({
                url: '<%= remove_from_compare_path %>?bus_type_id=<%=params[:bus_type_id] %>&id=' + id,
                type: 'get',
                dataType: 'html',
                processData: false,
                success: function (data) {
                    $('#compare-added-buses').html(data);
                    $('#chk_' + id).attr('checked', false);
                    count = parseInt(count_v) - 1;
                    $('#count_value').val(count);
                }
            });
        }
    }
    function slideDown() {
        $("#compare_toolbar").toggle();
    }
</script>
<div id='compare-added-buses'>
  <%= render :partial => 'shared/compare_added_buses' %>
</div>

app/views/shared/_devise_errors.html.erb
<% if !notice.nil? %>
	<div class="contactSuccessMessage"><%= notice %></div>
<% end %>

<% if !alert.nil? %>
	<span class="error"><%= alert %></span>
<% end %>

app/views/shared/_header.html.erb
	<!-- header start -->
	<div class="headerContainer">
	  <div class="header"> <a href="/" class="mainLogo"><%= image_tag('mainLogo.png') %></a>
	    <ul class="mainMenu">
	      <li><%= link_to "<span>About Us</span>".html_safe, about_path %></li>
	      <li><%= link_to "<span>Services</span>".html_safe, services_path %></li>
	      <li><%= link_to "<span>Bus Listings</span>".html_safe, listings_path %></li>
	      <li><%= link_to "<span>Submit A Vehicle</span>".html_safe, submit_vehicle_path %></li>
	      <li><%= link_to "<span>Contact Us</span>".html_safe, contact_path %></li>
	    </ul>
	<% if dealer_signed_in? %>
    		<div style="margin-top:20px;text-align: right;">
	    		<%= link_to current_dealer.email+", ", edit_dealer_path(current_dealer) %>
	    		<%= link_to "Logout".html_safe, destroy_dealer_session_path %>
		</div>
    	<% else %>
    		<%= link_to "<img src='/assets/dealerLoginBg.png' alt='' />".html_safe, dealer_session_path, :class => 'dealerLoginBtn' %>
    	<% end %>
	    </div>
	</div>
	<!-- header end -->

app/views/shared/_menu_icons.html.erb
<div class="contentMenu">
  <div class="clear"></div>
  <% if params[:controller] == "admin/search" %>
    <a href="/admin/inventory?per_page=10"><div class="contentCaption"><img src="/assets/admin/icons/busIcon.png" alt="Inventory Listings"/>Search</div></a>
  <% else %>
    <a href="/admin/inventory?per_page=10"><div class="contentCaption"><img src="/assets/admin/icons/busIcon.png" alt="Inventory Listings"/>Inventory Listings</div></a>
  <% end %>
  <div class="menuIcons">
    <script>
      function submit_multiple_pdf(){
        var data = $('input:checkbox:checked.bus_check_box').map(function () {
          return "'"+this.value+"'";
        }).get();
        location.href = '<%= admin_export_to_pdf_multiple_path %>.pdf?ids=['+data+']';
      }
      function submit_multiple_excel(){
        var data = $('input:checkbox:checked.bus_check_box').map(function () {
          return "'"+this.value+"'";
        }).get();
        location.href = '<%= admin_export_to_xls_path %>?ids=['+data+']';
      }
      function submit_delete(){
        var data = $('input:checkbox:checked.bus_check_box').map(function () {
          return "'"+this.value+"'";
        }).get();

        if (data != "") {
          if(data && confirm("Are you sure you want to delete these items?")){
            location.href = '<%= delete_inventory_path %>?ids=['+data+']';
          }
        } else {
          alert("Please select some records first!");
        }
      }
      function submit_zip(){
        var data = $('input:checkbox:checked.bus_check_box').map(function () {
          return "'"+this.value+"'";
        }).get();
        location.href = '<%= zip_inventory_path %>?ids=['+data+']';
      }
    </script>

    <div class="menuIcon">
      <%if current_user.class != User or (current_user.class == User and current_user.permission and ((current_user.permission.permission == "full_permission") or (current_user.permission.permission == "set_permission" and current_user.permission.add_inventory)))%>
        <%= link_to image_tag("/assets/admin/icons/addVehicle.png", :alt => "Add Vehicle"), new_admin_inventory_path %><br/>Add<br/>Vehicle
      <%else%>
        <a href="/assets/admin/denied.jpg" rel="facebox" style="text-decoration: none;color: black;">
          <%= image_tag("/assets/admin/icons/addVehicle.png") %><br/>Add<br />Inventory
        </a>
      <%end%>
    </div>
    <div class="menuIcon"><a href=""><img src="/assets/admin/icons/manageViews.png" alt="Manage Views"/><br/>Manage<br/>Views</a></div>

    <% if (params[:controller] == "admin/inventory" or params[:controller] == "admin/sold_inventory") and (params[:action] == "index" or params[:action] == "search") %>
      <div class="menuIcon"><%= link_to image_tag("/assets/admin/icons/liveInventory.png", :alt => "Live Inventory"), listings_path, :target => "_blank" %><br/>Live<br/>Inventory</a></div>
      <a href="#" target="_blank"><div class="menuIcon" onclick="submit_multiple_pdf()"><%= image_tag("/assets/admin/icons/exportToPdf.png", :alt => "Export To PDF") %><br/>Export<br/>To PDF</div></a>
      <a href="#" target="_blank"><div class="menuIcon" onclick="submit_multiple_excel()"><%= image_tag("/assets/admin/icons/exportToExcel.png", :alt => "Export to Excel") %><br/>Export<br/>To Excel</div></a>
      <div class="menuIcon"><%= link_to image_tag("/assets/admin/icons/soldInventory.png", :alt => "Sold Inventory"), admin_sold_inventory_index_path %><br/>Sold<br/>Inventory</a></div>
      <div class="menuIcon"><%= link_to image_tag("/assets/admin/icons/soldInventory.png", :alt => "Sold Inventory"), admin_inventory_index_path(:pending => true) %><br/>pending<br/>Inventory</a></div>
      <a href="#"><div class="menuIcon" onclick="submit_zip()"><img src="/assets/admin/icons/downloadImages.png" alt="Download Images"/><br/>Download<br/>Images</div></a>
      <%if current_user.class != User or (current_user.class == User and current_user.permission and ((current_user.permission.permission == "full_permission") or (current_user.permission.permission == "set_permission" and current_user.permission.ability_delete)))%>
        <a href="#"><div class="menuIcon" onclick="submit_delete()"><img src="/assets/admin/icons/delete.png" alt="Delete"/><br/>Delete</div></a>
      <%else%>
        <a href="/assets/admin/denied.jpg" rel="facebox" style="text-decoration: none;color: black;">
          <%= image_tag("/assets/admin/icons/delete.png") %><br/>Delete
        </a>
      <%end%>

    <% end %>

    <% if params[:controller] == "admin/inventory" and params[:action] == "edit" %>
      <div class="menuIcon"><%= link_to image_tag("/assets/admin/icons/liveInventory.png", :alt => "Live Inventory"), listing_path(@inventory.stock_id), :target => "_blank" %><br/>Live<br/>Inventory</a></div>
      <div class="menuIcon">
        <%if current_user.class != User or (current_user.class == User and current_user.permission and ((current_user.permission.permission == "full_permission") or (current_user.permission.permission == "set_permission" and current_user.permission.ability_delete)))%>
          <%= link_to image_tag("/assets/admin/icons/delete.png", :alt => "Delete"), admin_inventory_path(@inventory.id), :confirm => "Are you sure you want to delete this record?", :method => :delete %><br/>Delete<br/>Inventory</a>
        <%else%>
          <a href="/assets/admin/denied.jpg" rel="facebox">
            <%= image_tag("/assets/admin/icons/action4.png") %>
          </a>
        <%end%>

      </div>
    <% end %>

    <div class="clear"></div>

  </div>
  <div class="clear"></div>
</div>

app/views/shared/_module_contacts.html.erb
<div class="contentTable">
  <table width="100%">
    <tr class="tableTop">
      <td colspan="15">
        <div class="tableTopHeader">
          <span>Latest 5 Contacts</span>

          <div class="clear"></div>
        </div>
        <div class="headerDivider"></div>
      </td>

    </tr>
    <% if @contact.count == 0 %>
      <tr>
        <td><h2>No records here.../h2></td>
      </tr>
    <% else %>
      <tr class="bus_row">
        <th width="5%" class="actions_col"><a href="#">Actions</a></th>
        <th width="5%">Contact ID</th>
        <th width="10%">Name</th>
        <th width="10%">Email</th>
        <th  width="15%">Phone</th>
        <th  width="40%">Comment</th>
      </tr>
      <% @contact.each do |contact| %>
        <tr>

          <td class="actions">

            <%if current_user.class != User or (current_user.class == User and current_user.permission and ((current_user.permission.permission == "full_permission") or (current_user.permission.permission == "set_permission" and current_user.permission.ability_delete)))%>
              <%= link_to image_tag("/assets/admin/icons/action4.png"), admin_contact_path(contact.id), method: :delete, :alt => "Delete This Contact", :confirm => "Are you sure you want to delete this Contact" %>
            <%else%>
              <a href="/assets/admin/denied.jpg" rel="facebox">
                <%= image_tag("/assets/admin/icons/action4.png") %>
              </a>
            <%end%>
          </td>
          <td><%= contact.id %></td>
          <td><%= link_to contact.name, admin_contact_path(contact.id) %></td>
          <td><%= contact.email %></td>
          <td><%= contact.phone %></td>
          <td width="160"><%= contact.comments[0,20] %></td>
        </tr>
      <% end %>
    <% end %>
  </table>
</div>

app/views/shared/_module_sold.html.erb
	 <div class="contentTable">
	  <table width="100%">
	   <tr class="tableTop">
	<td colspan="15">
	    <div class="tableTopHeader">                            
	        <span>Latest 5 Sold</span>
	
	        <div class="clear"></div>
	    </div>
	    <div class="headerDivider"></div>
	</td>
	
	</tr>
	<% if @inventory.count == 0 %>
	<tr>
		<td><h2>No records here...</h2></td>
	</tr>
	<% else %>
	<tr class="bus_row">
	
		<th class="actions_col" width="5%" ><a href="#">Actions</a></th>
		<th width="5%">ID</th>
		<th width="10%">Stock ID</th>
		<th width="10%">Status</th>
		<th width="15%">Sold Date</th>
		<th width="40%">Sold Price</th>
	</tr>
	<% @inventory.each do |inventory| %>
	<tr>
	
	<td class="actions">
          <%if current_user.class != User or (current_user.class == User and current_user.permission and ((current_user.permission.permission == "full_permission") or (current_user.permission.permission == "set_permission" and current_user.permission.ability_delete)))%>
	    <%= link_to image_tag("/assets/admin/icons/action4.png"), admin_inventory_path(inventory.id), method: :delete, :alt => "Delete This Inventory", :confirm => "Are you sure you want to delete this Inventory?" %>
           <%else%>
              <a href="/assets/admin/denied.jpg" rel="facebox">
                <%= image_tag("/assets/admin/icons/action4.png") %>
              </a>
            <%end%>
	</td>
		<td><%= link_to inventory.id, edit_admin_inventory_path(inventory.id) %></td>	
		<td><%= inventory.stock_id %></td>
		<td><%= image_tag("admin/icons/"+inventory.status_image, :alt => "Inventory") %>
		<td><%= inventory.sold_date.to_s[0,16] %></td>
		<td><%= number_to_currency(inventory.sold_price) %></td>
	</tr>
	<% end %>
	<% end %>
	   </table>
	  </div>

app/views/shared/_pending.html.erb
<div class="contentTable">
  <table width="100%">
    <tr class="tableTop">
      <td colspan="15">
        <div class="tableTopHeader">
          <span>Latest Customer Additions</span>

          <div class="clear"></div>
        </div>
        <div class="headerDivider"></div>
      </td>

    </tr>
    <% if @buses.count == 0 %>
      <tr>
        <td><h2>No records here...</h2></td>
      </tr>
    <% else %>
      <tr class="bus_row">

        <th class="actions_col" width="5%" ><a href="#">Actions</a></th>
        <th width="5%">ID</th>
        <th width="10%">Stock ID</th>
        <th width="10%">Status</th>
        <th width="15%">Action</th>
      </tr>
      <% @buses.each do |inventory| %>
        <tr>

          <td class="actions">
            <%if current_user.class != User or (current_user.class == User and current_user.permission and ((current_user.permission.permission == "full_permission") or (current_user.permission.permission == "set_permission" and current_user.permission.ability_delete)))%>
              <%= link_to image_tag("/assets/admin/icons/action4.png"), admin_inventory_path(inventory.id), method: :delete, :alt => "Delete This Inventory", :confirm => "Are you sure you want to delete this Inventory?" %>
            <%else%>
              <a href="/assets/admin/denied.jpg" rel="facebox">
                <%= image_tag("/assets/admin/icons/action4.png") %>
              </a>
            <%end%>
          </td>
          <td><%= inventory.stock_id %></td>
          <td><%= inventory.id %></td>
          <td><%= inventory.status %></td>
          <td><%= link_to 'Approve', "/admin/inventory/update_status?id=#{inventory.id}" %></td>
        </tr>
      <% end %>
    <% end %>
  </table>
</div>