config/routes.rb
Buscms::Application.routes.draw do

  get "admin/export/to_xls", :as => :export_to_xls
  get "admin/export/to_pdf", :as => :export_to_pdf

  devise_for :admins
  devise_for :dealers, :controllers => {:confirmations => "confirmations"}
  devise_for :users

  match 'admin/bus_type' => 'admin/bus_types#create', :via => [:post, :put]
  match 'admin/chasis_makes' => 'admin/chasis_makes#create', :via => [:post, :put]
  match 'admin/images' => 'admin/images#create', :via => [:post, :put]
  match 'admin/inventory/search' => 'admin/inventory#search', :via => [:get, :post]
  match 'admin/inventory/update_status' => 'admin/inventory#update_status', :via => [:get, :post]
  match 'admin/leads/search_leads' => 'admin/leads#search_leads', :via => [:get, :post]
  match 'admin/export/to_xls' => 'admin/export#to_xls', :via => [:get, :post]
  match 'admin/export/to_xls_leads' => 'admin/export#to_xls_leads', :via => [:get, :post]
  match 'admin/export/to_pdf' => 'admin/export#to_pdf', :via => [:get, :post]
  match 'admin/export/to_pdf_multiple' => 'admin/export#to_pdf_multiple', :via => [:get, :post]
  match 'admin/export/to_pdf_multiple_leads' => 'admin/export#to_pdf_multiple_leads', :via => [:get, :post]
  match 'admin/export/destroy' => 'admin/inventory#destroy', :via => [:get], :as => :delete_inventory
  match 'admin/dealers/destroy' => 'admin/dealers#destroy', :via => [:get], :as => :delete_dealers
  match 'admin/users/destroy' => 'admin/users#destroy', :via => [:get], :as => :delete_users
  match 'admin/leads/destroy' => 'admin/leads#destroy', :via => [:get], :as => :delete_leads
  match 'admin/export/to_zip' => 'admin/export#to_zip', :via => [:get], :as => :zip_inventory
  match 'addtocompare' => 'home#addtocompare', :via => [:get], :as => :add_to_compare
  match 'removefromcompare' => 'home#removefromcompare', :via => [:get], :as => :remove_from_compare
  match 'admin/adds/delete_bulk_ads' => 'admin/adds#delete_bulk_ads', :via => [:get], :as => :remove_from_add
  match 'admin/adds/filter' => 'admin/adds#filter', :via => [:get], :as => :filter_add
  match '/generate_stock_id' => 'home#generate_stock_id', :via => [:get], :as => :generate_stock_id

  namespace :admin do
    resources :users
    match 'users/confirm_user_account/:id' => 'users#confirm_account', :via => [:get], :as => :confirm_user_account
    match 'dealers/confirm_dealer_account/:id' => 'dealers#confirm_account', :via => [:get], :as => :confirm_dealer_account
    match 'users/deactivate_account/:id' => 'users#deactivate_account', :via => [:get], :as => :deactivate_account
    match 'settings/update_settings' => 'settings#update_settings'
    match 'leads/send_email' => 'leads#send_email', :via => :post
    match 'leads/create_blast' => 'leads#create_blast', :via => :get
    match 'leads/remove_stock_session' => 'leads#remove_stock_session', :via => :get
    match 'leads/add_stock' => 'leads#add_stock', :via => :get
    match 'leads/blast_step3' => 'leads#blast_step3', :via => :get
    match 'leads/blast_last_step' => 'leads#blast_last_step', :via => :post
    match 'leads/send_blast' => 'leads#send_blast', :via => :post
    match 'leads/search' => 'leads#search'

    match 'search' => 'search#index'
    match 'recyclebins/restore' => 'recyclebins#restore'
    match 'recyclebins/restore_all' => 'recyclebins#restore_all'
    match 'recyclebins/restore_all_current_bin' => 'recyclebins#restore_all_current_bin'
    match 'recyclebins/empty_all' => 'recyclebins#empty_all'
    match 'recyclebins/empty_bin' => 'recyclebins#empty_bin'
    match 'recyclebins/set_delete_timer' => 'recyclebins#set_delete_timer'

    resources :images #, :only => [:index, :create, :destroy]
    resources :bus_type
    resources :inventory

    resources :contact
    resources :sold_inventory
    resources :settings
    resources :leads
    resources :chasis_makes
    resources :body_makes
    resources :dealers
    resources :stats
    resources :recyclebins
    resources :adds 
  end
  match 'listings/compare' => 'listings#compare', :via => :get
  match 'listings/search' => 'listings#search'
  match 'listings/:slug' => 'listings#index', :via => :get, :as => :buses_search, :slug => /[a-z-]{0,}/
  match 'contact/new_lead' => 'contact#new_lead', :via => [:post], :as => :new_lead

  resources :contact
  resources :listings, :only => [:show, :index, :search , :send_mail_to_friend, :send_inquiry_received_email] do
    collection do
      match 'search' => 'listings#search', :via => :get, :as => :search
      post 'send_friend_mail' => 'listings#send_mail_to_friend'
      post 'send_inquiry_received_email' => 'listings#send_inquiry_received_email'
    end
  end
  resources :dealer

  match 'cron/cron_to_update_bus_stats' => 'home#cron_to_update_bus_stats'
  match "/admin", :to => redirect("/admin/dashboard")
  match 'admin/dashboard' => 'admin/dashboard#index', :via => [:get, :post], :as => :admin_dashboard
  match 'services' => 'home#services', :as => :services
  match 'about' => 'home#about', :as => :about
  match 'contact' => 'contact#index', :as => :contact
  match 'submit_vehicle' => 'home#submit_vehicle', :as => :submit_vehicle
  match 'dealer' => 'dealer#index', :as => :dealer
  match 'add_new_vehicle' => 'home#add_new_vehicle', :as => :add_new_vehicle
  match 'compare' => 'home#compare', :as => :compare
  match 'temp' => 'temp_uploader#upload' , :as => :temp
  match '/admin/adds/update' => 'admin/adds#update'

  root :to => 'listings#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "new_desgin"

  def index
    @var = "Welcome ! Under Construction! "
  end

  def services

  end

  def about

  end

  def contact

  end

  def show
    # TODO: Duplication here - Refactor
    @bus_types = BusType.all
    @bus_type = BusType.find_by_slug(params[:slug]) || not_found
    @all = @bus_type.buses.where(:live => "yes").paginate :page => params[:page], :per_page => 5
    @compare_list = Bus.where(:stock_id => session[:buses])
    #binding.pry
  end

  def addtocompare
    session[:buses] ||= Array.new
    if session[:buses].try(:count) < 7
      session[:buses] = session[:buses].push(params[:id]).uniq
    end
    @compare_list = Bus.where(:stock_id => session[:buses])
    render :partial => 'shared/compare_added_buses'
    #redirect_to (request.referer)?(request.referer):root_path , :notice => "Added to compare list"
  end

  def compare
    @bus_types = BusType.all
    @listing = Bus.where(:stock_id => session[:buses]) if session[:buses]
    if session[:buses].blank?
      flash[:notice] = "No buses added for comparision"
      redirect_to "/"
    end
  end

  def removefromcompare
    session[:buses].delete_at(session[:buses].find_index(params[:id]))
    if request.xhr?
      @compare_list = Bus.where(:stock_id => session[:buses])
      render :partial => 'shared/compare_added_buses'
    else
      redirect_to request.referer, :notice => "Removed from compare list"
    end
  end

  def submit_vehicle
    @bus_types = BusType.all
    @bus = Bus.new
    @bus.images.build
    @bus.build_seller
  end

  def add_new_vehicle
    #params[:bus][:state_id] = params[:bus][:state_id].to_i
    @bus = Bus.new(params[:bus])
    random_stock = generate_stock_id_num(params[:bus][:bus_type_id])
    @bus[:stock_id] = random_stock
    @bus[:vin] = random_stock+"_BY_VISITOR"
    @bus[:status] = "pending"
    @bus[:live] = "no"
    @bus[:featured] = "no"
    @bus[:posted_price] = "sale_price"
    @bus[:created_by] = "Visitor"
    @bus[:last_status_change_by] = "Visitor"
    @bus[:luggage] = "No"
    @bus[:rear_luggage] = "No"
    @bus.live = "no" if  params[:bus][:status] == "pending"
    if @bus.save
      flash[:notice] = "Vehicle Submitted for Approval!"
      redirect_to submit_vehicle_path
    else
      @bus.build_seller (params[:bus][:seller_attributes])
      @bus.images.build (params[:bus][:images])
      flash[:alert] = "There were some errors, Please fix those before proceeding!"
      render :submit_vehicle
    end
  end

  def cron_to_update_bus_stats
    username = Settings.get('ga_username')
    password = Settings.get('ga_password')
    profile_id = Settings.get('ga_profile_id')
    Garb::Session.login(username, password)
    profile = Garb::Management::Profile.all.detect { |p| p.web_property_id == profile_id }
    @buses = Bus.all
    date = Date.today
    @buses.each do |bus|
      bus_path = "/listings/"+bus.stock_id
      result = Exits.results(profile, :start_date => date, :end_date => date, :filters => {:page_path.eql => bus_path}) unless profile.nil?
      result.to_a.each do |res|
        stat = Stat.new
        stat.visits = res.pageviews
        stat.date = date
        stat.bus_id = bus.id
        stat.save
      end if result.present?
    end
    render :text => "OK"
  end

  def generate_stock_id
    render :text => generate_stock_id_num(params[:bus_type])
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_submit_vehicle.html.haml
#listing_content
  #listing_area
    #listing_results
      %h2
        %span.large_greytext
          Submit A Vehicle
    - if flash[:notice].present?
      %span.success= flash[:notice]
    - if flash[:alert].present?
      %span.error= flash[:alert]
  .clearfix
  .add-veh-area
    = form_for @bus, :url => add_new_vehicle_path, :html => {:multipart => true} do |f|
      - @bus.errors.full_messages.each do |msg|
        %span.error= msg
      / Bus Type Id
      .submitVehicle
        = f.label :bus_type_id, "Bus Type:"
      .selectSubmit
        = f.collection_select :bus_type_id, BusType.find(:all), :id, :name
      %br/
      / Chasis Make Id
      .submitVehicle
        = f.label :chasis_make_id, "Chasis Make:"
      .selectSubmit
        = f.collection_select :chasis_make_id, ChasisMake.find(:all), :id, :name
      %br/
      / Year
      .submitVehicle
        = f.label :year, "Year:"
      .selectSubmit
        = f.select :year, (DateTime.now.year - 30)..(DateTime.now.year), {:include_blank => "Select Year"}
      %br/
      / Chasis Model
      .submitVehicle
        = f.label :chasis_model, "Chasis Model:"
      .selectSubmit
        = f.text_field :chasis_model
      %br/
      / Body Make ID
      .submitVehicle
        = f.label :body_make_id, "Body Make:"
      .selectSubmit
        = f.collection_select :body_make_id, BodyMake.find(:all), :id, :name
      %br/
      / Body Model
      .submitVehicle
        = f.label :body_model, "Body Model:"
      .selectSubmit
        = f.text_field :body_model
      %br/
      / Mileage
      .submitVehicle
        = f.label :mileage, "Mileage:"
      .selectSubmit
        = f.text_field :mileage
        (in kms)
      %br/
      / Passengers
      .submitVehicle
        = f.label :passengers, "Passengers:"
      .selectSubmit
        = f.text_field :passengers
      %br/
      / Color
      .submitVehicle
        = f.label :exterior_color, "Exterior Color:"
      .selectSubmit
        = f.text_field :exterior_color
      %br/
      / Color
      .submitVehicle
        = f.label :interior_color, "Interior Color:"
      .selectSubmit
        = f.text_field :interior_color
      %br/
      / Wheelchair Capacity
      .submitVehicle
        = f.label :wheelchair_capacity, "Wheelchair Capacity:"
      .selectSubmit
        = f.text_field :wheelchair_capacity
      %br/
      / Sale Price
      .submitVehicle
        = f.label :sale_price, "Sale Price:"
      .selectSubmit
        = f.text_field :sale_price
      %br/
      / Sale Price
      .submitVehicle
        = f.label :vehicle_length, "Vehicle Length:"
      .selectSubmit
        = f.text_field :vehicle_length
        (in ft.)
      %br/
      / Location
      .submitVehicle
        = f.label :location, "Location:"
      .selectSubmit
        = f.select :location, ["USA", "Canada"] , { :include_blank => "Country (any)" } , :id => "country"
      .clearfix
      %br/
      .submitVehicle
        = f.label :location, "State:"
      .selectSubmit
        %select.state#state_empty{:name => "state", :tabindex => "2"}
        = f.select :state_id , State.where("country_id = ? ",Country.find_by_name("United States").id).collect {|c| [ c.name, c.id ] } , { :include_blank => "State (any)" } , :id => "state_usa" , :tabindex => "2" , :class => "state" , :style => "display: none"
        = f.select :state_id , State.where("country_id = ? ",Country.find_by_name("Canada").id).collect {|c| [ c.name, c.id ] } , { :include_blank => "State (any)" } , :id => "state_canada" , :tabindex => "2"  , :class => "state" , :style => "display: none"
      .clearfix
      %br/
      / Location
      .submitVehicle
        = f.label :engine, "Engine:"
      .selectSubmit
        = f.text_field :engine
      %br/
      / Description
      .submitVehicle
        Description:
      .selectSubmit
        = f.text_area :vehicle_description, :rows => 10, :cols => 40
      %br/
      %br/
      = f.fields_for :images do |builder|
        .submitVehicle
          = builder.label :image, "Add Photo"
        .selectSubmit
          = builder.file_field :image
        %br/
      .submitVehicleContent
        %h3.customTitle1 Add Contact Information
        = f.fields_for :seller do |sf|
          / Contact Name
          .submitVehicle
            = sf.label :name, "Name:"
          .selectSubmit
            = sf.text_field :name
          %br/
          / Contact Phone
          .submitVehicle
            = sf.label :phone, "Phone:"
          .selectSubmit
            = sf.text_field :phone
          %br/
          / Contact Email
          .submitVehicle
            = sf.label :email, "Email:"
          .selectSubmit
            = sf.text_field :email
          %br/
          / Contact Postal Code
          .submitVehicle
            = sf.label :postal_code, "Postal Code:"
          .selectSubmit
            = sf.text_field :postal_code
          %br/
          / Contact Comments
          .submitVehicle
            = sf.label :comments, "Comments:"
          .selectSubmit
            = sf.text_area :comments, :rows => 10, :cols => 40
          %br/
        = f.submit "Submit", :id => "contactSubmitBtn"

app/views/home/index.html.erb
<% content_for :title, "Home" %>

app/views/home/submit_vehicle.html.erb
<!-- bus name and price starts-->
<div id="detail_titlearea" xmlns="http://www.w3.org/1999/html">
  <div class="detail_headings">
    <div class="compare_heading_left">
      <h1>Post Your Vehicle </h1>

    </div>
  </div>
</div>
<!-- bus name and price ends-->
<div id="detail_content">
  <!-- inventory details start -->
  <div id="compare_specs_area">

    <!-- Vehicle specs start-->
    <div id="post_vehicle_panel" class="post_vehicle_form">
      <%= form_for @bus, :url => add_new_vehicle_path, :html => {:multipart => true} do |f| %>
          <% if flash[:notice].present? %>
              <p class="success"><%= flash[:notice] %></p>
          <% end %>
          <%- if flash[:alert].present? %>
              <p class="error"><%= flash[:alert] %></p>
          <% end %>
          <%- @bus.errors.full_messages.each do |msg| %>
              <span class="error-vehicle"><%= msg %></span>
          <% end %>
          <p>Please fill out the form below and submit your vehicle.</p></br>
          <p class="style1">* Required fields.</p>

          <p><br/>
            <span class="dealer_form_title">Vehicle Information</span><br/>
            Bus Type * <br/>


            <%= f.collection_select :bus_type_id, BusType.find(:all), :id, :name %>
            <br/><br/>
            Year * <br/>
            <%= f.select :year, (DateTime.now.year - 30)..(DateTime.now.year), {:include_blank => "Select Year"} %>
            <br/><br/>
            Price * <br/>
            <%= f.text_field :sale_price %>
            <br/><br/>
            Body Make * <br/>
            <%= f.collection_select :body_make_id, BodyMake.find(:all), :id, :name %>
            <br/><br/>
            Body Model * <br/>
            <%= f.text_field :body_model %>
            <br/><br/>
            Chasis Make * <br/>
            <%= f.collection_select :chasis_make_id, ChasisMake.find(:all), :id, :name %>
            <br/><br/>
            Chasis Body * <br/>
            <%= f.text_field :chasis_model %>
            <br/><br/>
            Mileage(in kms) * <br/>
            <%= f.text_field :mileage %>
            <br/><br/>
            Passengers * <br/>
            <%= f.text_field :passengers %>
            <br/><br/>
            Exterior Color * <br/>
            <%= f.text_field :exterior_color %>
            <br/><br/>
            Interior Color * <br/>
            <%= f.text_field :interior_color %>
            <br/><br/>
            Wheelchair Capacity * <br/>
            <%= f.text_field :wheelchair_capacity %>
            <br/><br/>
            Vehicle Length (in ft)<br/>
            <%= f.text_field :vehicle_length %>
            <br/><br/>
            Engine<br/>
            <%= f.text_field :engine %>
            <br/><br/>
            Country *<br/>
            <%= f.select :location, ["USA", "Canada"], {:include_blank => "Country (any)"}, :id => "country" %>
            <br/>
            <br/>
            <br/>
            State/Province *<br/>
            <select name="state" id="state_empty" tabindex="2">

            </select>
            <%= f.select :state_id, State.where("country_id = ? ", Country.find_by_name("United States").id).collect { |c| [c.name, c.id] }, {:include_blank => "State (any)"}, :id => "state_usa", :tabindex => "2", :class => "state", :style => "display: none" %>
            <%= f.select :state_id, State.where("country_id = ? ", Country.find_by_name("Canada").id).collect { |c| [c.name, c.id] }, {:include_blank => "State (any)"}, :id => "state_canada", :tabindex => "2", :class => "state", :style => "display: none" %>
            <br/><br/><br/>
            Vehicle Description <br/>
            <%= f.text_area :vehicle_description, :rows => 10, :cols => 40 %>
            <br/><br/><br/>
            <span class="orange_text">Attach Main Image (5MB max size)</span> *<br/>
            <%= hidden_field_tag "image_count", 0 %>
            <%= f.fields_for :images do |builder| %>
                <input type="hidden" name="MAX_FILE_SIZE" value="500"/>

                <div class="upload_field" id="image-upload"><%= builder.file_field :image %></div>
            <% end %>
            <a class="attach_image_link" onclick="attach_another_image()" href="javascript:">Attach Another Image</a>
            <br/><br/><br/>
            <br/>
            <span class="dealer_form_title">Contact Information</span><br/>
            <%= f.fields_for :seller do |sf| %>
                Company Name <br/>
                <%= sf.text_field :name %>
                <br/><br/>
                Name <br/>
                <%= sf.text_field :phone %>
                <br/>
                <br/>

                Email <br/>
                <%= sf.text_field :email %><br/><br/>

                Zip/Postal Code <br/>
                <%= sf.text_field :postal_code %><br/></br/>
                Comments <br/>
                <%= sf.text_area :comments, :rows => 10, :cols => 40 %>
                <br/>
                <br/>
                <br/>
            <% end %>

            <%= f.submit "Submit", :id => "contactSubmitBtn", :class => "admin_login_btn" %>
      <% end %>

    </div>
    <!-- vehicle specs end -->
  </div>
</div>
<!-- listing content ends-->
<div class="clearfooter"></div>
<!-- wrapper ends-->

<!-- footer start -->


<!-- footer end -->

app/views/home/x_submit_vehicle.html.erb
<%= content_for :title, "Submit A Vehicle" %>

<div class="pageContent">
	<div class="box">
		<div class="aboutBoxLargeTop"></div>
			<div class="servicesBox">
				<div class="submitVehicleContent">
				<% if flash[:notice].present? %>
					<span class="success"><%= flash[:notice]  %></span>
				<% end %>
				
				<% if flash[:alert].present? %>
					<span class="error"><%= flash[:alert] %></span>
				<% end %>
				
				<h3 class="customTitle1">Submit A Vehicle</h1>
				<%= form_for @bus, :url => add_new_vehicle_path, :html => {:multipart => true} do |f| %>
					<% @bus.errors.full_messages.each do |msg| %>
						<span class="error"><%= msg %></span>
					<% end %>
					<!-- Bus Type Id  -->
					<div class="submitVehicle">
                   		<%= f.label :bus_type_id, "Bus Type:" %>
                    </div>
                    
                    <div class="selectSubmit">
                   		<%= f.collection_select :bus_type_id, BusType.find(:all), :id, :name %>
                    </div>
                    
                    <br/>
                	
					<!-- Chasis Make Id  -->
					<div class="submitVehicle">
						<%= f.label :chasis_make_id, "Chasis Make:" %>
					</div>
					
					<div class="selectSubmit">
						<%= f.collection_select :chasis_make_id, ChasisMake.find(:all), :id, :name %>
					</div>
                    
                    <br/>
                    
                    <!-- Year -->
					<div class="submitVehicle">
						<%= f.label :year, "Year:" %>
					</div>
					
					<div class="selectSubmit">
						<%= f.select :year, (DateTime.now.year - 30)..(DateTime.now.year), {:include_blank => "Select Year"} %>
					</div>
					
					<br/>
                    
                    <!-- Chasis Model -->
					<div class="submitVehicle">
						<%= f.label :chasis_model, "Chasis Model:" %>
					</div>
					
					<div class="selectSubmit">
						<%= f.text_field :chasis_model %>
					</div>
                     
                    <br/>
					
                    <!-- Body Make ID    -->
                    	<div class="submitVehicle">
						<%= f.label :body_make_id, "Body Make:" %>
					</div>
					
					<div class="selectSubmit">
						<%= f.collection_select :body_make_id, BodyMake.find(:all), :id, :name %>
					</div>
                     
                    <br/>
                    
                    <!--  Body Model  -->
                    <div class="submitVehicle">
						<%= f.label :body_model, "Body Model:" %>
					</div>
					
					<div class="selectSubmit">
						<%= f.text_field :body_model %>
					</div>
                     
                    <br/>
                    
                    <!--  Mileage -->
					<div class="submitVehicle">
						<%= f.label :mileage, "Mileage:" %>
					</div>
					
					<div class="selectSubmit">
						<%= f.text_field :mileage %> (in kms)
					</div>
                     
                    <br/>
	
					<!--  Passengers -->
					<div class="submitVehicle">
						<%= f.label :passengers, "Passengers:" %>
					</div>
					
					<div class="selectSubmit">
						<%= f.text_field :passengers %>
					</div>
											
                    <br/>
                    
                    	<!--  Color -->
					<div class="submitVehicle">
						<%= f.label :exterior_color, "Exterior Color:" %>
					</div>
					
					<div class="selectSubmit">
						<%= f.text_field :exterior_color %>
					</div>
											
                    <br/>
                    
                    <!--  Color -->
					<div class="submitVehicle">
						<%= f.label :interior_color, "Interior Color:" %>
					</div>
					
					<div class="selectSubmit">
						<%= f.text_field :interior_color %>
					</div>
                    
                    <br/>
                    
                    
                    <!-- Wheelchair Capacity -->
					<div class="submitVehicle">
						<%= f.label :wheelchair_capacity, "Wheelchair Capacity:" %>
					</div>
					
					<div class="selectSubmit">
						<%= f.text_field :wheelchair_capacity %>
					</div>
                    
                    <br/>
                    
                    <!-- Sale Price-->
					<div class="submitVehicle">
						<%= f.label :sale_price, "Sale Price:" %>
					</div>
					
					<div class="selectSubmit">
						<%= f.text_field :sale_price %>
					</div>
											
                    <br/>
                    
                    <!-- Sale Price-->
					<div class="submitVehicle">
						<%= f.label :vehicle_length, "Vehicle Length:" %>
					</div>
					
					<div class="selectSubmit">
						<%= f.text_field :vehicle_length %> (in ft.)
					</div>
											
                    <br/>
                    
					<!-- Location -->
					<div class="submitVehicle">
						<%= f.label :location, "Location:" %>
					</div>
					
					<div class="selectSubmit">
						<%= f.select :location, ["USA", "Canada"] %>
					</div>
											
                    <br/>
                    
                    <!-- Location -->
					<div class="submitVehicle">
						<%= f.label :engine, "Engine:" %>
					</div>
					
					<div class="selectSubmit">
						<%= f.text_field :engine %>
					</div>
											
                    <br/>
                    
                    	<!-- Description -->
					<div class="submitVehicle">
						Description:
					</div>
					
					<div class="selectSubmit">
						<%= f.text_area :vehicle_description, :rows => 10, :cols => 40 %>
					</div>
											
                    <br/>
                    <br/>
                		<%= f.fields_for :images do |builder| %>
                			<div class="submitVehicle">
                				<%= builder.label :image, "Add Photo"%>
                			</div>
                			<div class="selectSubmit">
							<%= builder.file_field :image %>
						</div>
						<br/>
					<% end %>
					
					
					
				</div>
				
				<div class="submitVehicleContent">
	              	<h3 class="customTitle1">Add Contact Information</h3>
	              		<%= f.fields_for :seller do |sf| %>
	              		<!-- Contact Name-->
						<div class="submitVehicle">
	                   		<%= sf.label :name, "Name:" %>
	                    </div>
	                    
	                    <div class="selectSubmit">
	                   		<%= sf.text_field :name %>
	                    </div>
	                    
	                    <br/>
	                    
	                    <!-- Contact Phone-->
						<div class="submitVehicle">
	                   		<%= sf.label :phone, "Phone:" %>
	                    </div>
	                    
	                    <div class="selectSubmit">
	                   		<%= sf.text_field :phone %>
	                    </div>
	                    
	                    <br/>
	                    
	                    	<!-- Contact Email-->
						<div class="submitVehicle">
	                   		<%= sf.label :email, "Email:" %>
	                    </div>
	                    
	                    <div class="selectSubmit">
	                   		<%= sf.text_field :email %>
	                    </div>
	                    
	                    <br/>
	                    
	                    <!-- Contact Postal Code-->
						<div class="submitVehicle">
	                   		<%= sf.label :postal_code, "Postal Code:" %>
	                    </div>
	                    
	                    <div class="selectSubmit">
	                   		<%= sf.text_field :postal_code %>
	                    </div>
	                    
	                    <br/>
	                    
	                    
	                    <!-- Contact Comments-->
						<div class="submitVehicle">
	                   		<%= sf.label :comments, "Comments:" %>
	                    </div>
	                    
	                    <div class="selectSubmit">
	                   		<%= sf.text_area :comments, :rows => 10, :cols => 40 %>
	                    </div>
	                    
	                    <br/>
	              		<% end %>
	              		<%= f.submit "", :id => "contactSubmitBtn" %>
              	</div>
              		
				<% end %>
			</div>
		<div class="aboutBoxLargeBottom"></div>
	</div>
</div>